export type WhyThisMatters = { businessImpact: string; operationalImpact: string; missionImpact: string };
export type EoxIndicator = { name: string; status: string; value: string; basis: string; measurement?: { numerator: number; denominator: number } };
export type EoxRecommendation = { recommendationId: string; title: string; status: string; suggestedNavigation: string; whyThisMatters: WhyThisMatters };
export type EoxAssessment = {
  schemaVersion: "1.0.0";
  recordType: "nexus_executive_operating_loop";
  generatedAt: string;
  executiveState: { active: string; source: string; reason: string };
  loop: Array<{ stage: string; active: boolean; status: string }>;
  executiveNarrative: { text: string; status: string; source: string };
  executiveBrief: { currentOperationalPosture: string; operationalReadiness: Record<string, unknown>; currentRisks: EoxAttention[]; currentOpportunities: Array<Record<string, unknown>>; currentApprovals: Record<string, unknown>; outstandingRecommendations: EoxRecommendation[] };
  operationalHealth: EoxIndicator[];
  attentionQueue: EoxAttention[];
  recommendedActions: EoxRecommendation[];
  missionTimeline: Array<{ event: string; occurredAt: string; source: string; whyThisMatters: string }>;
  operationalUnderstanding: EoxIndicator[];
  briefing: { available: boolean; interactionOwner: string; presentationSections: string[] };
  truth: Record<string, unknown>;
  limitations: string[];
};
export type EoxAttention = { significance: string; category: string; title: string; whyThisMatters: WhyThisMatters };
