uploads = []
outputs = []

[[generated]]
id = "yStbAMbW776llCdCQ96YU"
uri = "file://public/images/bg-grid.png"
type = "image"
title = "Dark high-tech grid background"

[[generated]]
id = "FURjNMPpW09oCdrmNBgxc"
uri = "file://public/images/architecture.png"
type = "image"
title = "Abstract glowing layered architecture"

[[generated]]
id = "v81kkQfw1IgLYoH0pItm9"
uri = "file://public/images/ledger.png"
type = "image"
title = "Secure ledger abstract visualization"
